
function experimental_settings()

fig = figure;
    set(fig, 'MenuBar', 'none');
    set(fig, 'ToolBar', 'none');
    set(fig,  'Resize',  'off');

% TITLE ==================================================================
page_header = uicontrol(fig,'Style', 'Text',... %Spesifying what kinf of object to be added
                    'Units', 'Normalized',... %used for positioning objects fractional units from 0-1 so images will change if page window changes 
                    'Position', [0.1 0.8 0.8 0.2],...
                    'FontSize', 22, ...
                    'FontWeight', 'Bold',...% Last two digits in vectors, is in order from left to right - hieght, width. First two vectors are cooridinates of object from left point in figure. Limits are 1 for the furthest point to the right, 0 is furthest to left for width, and then the same for hieght
                    'String', 'Experimental Settings');

back_button = uicontrol(fig,'style', 'pushbutton',... 
                    'string', 'Back', ...
                    'units', 'normalized',... 
                    'position', [0.05 0.8 0.1 0.12],... 
                    'callback', @back_button_function);

                
 
save_button = uicontrol(fig,'style', 'pushbutton',... 
                    'string', 'Save Settings', ...
                    'units', 'normalized',... 
                    'position', [0.77 0.8 0.2 0.06],... 
                    'callback', @save_exp_settings);
                
%LEFT SIDE: SCREEN SETUP ==================================================

pnl1 = uipanel(fig,'Title','Memory Load','FontSize',12, 'FontWeight','Bold',...
                'BackgroundColor','white',...
                'Position',[0.05 0.05 0.3 0.75]);
subpnl = uipanel(pnl1,'Position',[0.05, 0.7, 0.9, 0.9]);

subpnl2 = uipanel(pnl1,'Position',[0.05, 0.4, 0.9, 0.3]);

subpnl3 = uibuttongroup(pnl1,'Visible','off',...
                  'Position',[0.05, 0.01, 0.9, 0.39],...
                  'SelectionChangedFcn',@data_type_selection);
            

%NUMBER OF MEMORY ========================================================= 

mem_load = uicontrol(subpnl,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.05, 0.2, 0.9, 0.1],...
                    'FontSize', 8, ...
                    'FontWeight', 'normal',...
                    'String', 'Number of Memory loads');
                
%create an editable textbox object
mem_load_editbox = uicontrol(subpnl,'style','edit',...
                    'String', '5', ...
                    'units', 'normalized',...
                    'position', [0.3 0.1 0.4 0.1]);
                
%ITEMS PER MEMORY LOAD VECTOR==============================================

Item_per_memload = uicontrol(subpnl2,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.05 0.8 0.9 0.15],...
                    'FontSize', 8, ...
                    'FontWeight', 'normal',...
                    'String', 'Items Per Memory Load Vector');
                
%create an editable textbox object
Items_load_editbox = uicontrol(subpnl2,'style','edit',...
                    'units', 'normalized',...
                    'String', '11 2 3 4 5',...
                    'position', [0.05 0.6 0.9 0.2]);
                
%TRAILS PER MEMORY LOAD VECTOR============================================
 
 
Trails_per_memload = uicontrol(subpnl2,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.05 0.3 0.9 0.15],...
                    'FontSize', 8, ...
                    'FontWeight', 'normal',...
                    'String', 'Trails Per Memory Load Vector');
                
%create an editable textbox object
Trails_load_editbox = uicontrol(subpnl2,'style','edit',...
                    'units', 'normalized',...
                    'String', '30 30 30 30 30', ...
                    'position', [0.05 0.1 0.9 0.2]);
                
%DATA TYPE ================================================================

data_per_memload = uicontrol(subpnl3,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.05 0.8 0.9 0.15],...
                    'FontSize', 10, ...
                    'FontWeight', 'Bold',...
                    'String', 'Data Type');
              
% Create three radio buttons in the button group.


r1 = uicontrol(subpnl3,'Style',...
                  'radiobutton',...
                  'String','Integers',...
                  'Position',[4 60 59 30],...
                  'HandleVisibility','off');
              
r2 = uicontrol(subpnl3,'Style','radiobutton',...
                  'String','Letters',...
                  'Position',[4 35 59 30],...
                  'HandleVisibility','off');
r2_caps = uicontrol(subpnl3,'Style','pushbutton',...
                  'String','Capitalise On',...
                  'Position',[70 35 70 20],...
                  'HandleVisibility','off');
r3 = uicontrol(subpnl3,'Style','radiobutton',...
                  'String','Mixed',...
                  'Position',[4 10 59 30],...
                  'HandleVisibility','off');
 
%LEFT SIDE: SCREEN SETUP ==================================================

%TOP CENTRE RIGHT: SCREEN SETUP============================================
pnl2 = uipanel(fig,'Title','Save Options','FontSize',12, 'FontWeight','Bold',...
                'BackgroundColor','white',...
                'Position',[0.36 0.4 0.61 0.4]);
            
subpnl4 = uipanel(pnl2,'Position',[0.05, 0.55, 0.9, 0.4]);            
              
subpnl5 = uipanel(pnl2,'Position',[0.05, 0.1, 0.9, 0.5]);            
             
 
number_range = uicontrol(subpnl4,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.05 0.55 0.3 0.3],...
                    'FontSize', 8, ...
                    'FontWeight', 'Bold',...
                    'String', 'Number Range Vector');
                
number_range_editbox = uicontrol(subpnl4,'style','edit',...
                    'units', 'normalized',...
                    'HorizontalAlignment', 'center', ...
                    'String', '0 9', ...
                    'position', [0.05 0.3 0.3 0.3]);


letter_range = uicontrol(subpnl4,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.6 0.55 0.3 0.3],...
                    'FontSize', 8, ...
                    'FontWeight', 'Bold',...
                    'String', 'Letter Range');
                
letter_range_editbox = uicontrol(subpnl4,'style','edit',...
                    'units', 'normalized',...
                    'HorizontalAlignment', 'center', ...
                    'String', 'A Z', ...
                    'position', [0.6 0.3 0.3 0.3]);     
                
mixed_ratio_split = uicontrol(subpnl5,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.02 0.5 0.4 0.4],...
                    'FontSize', 8, ...
                    'FontWeight', 'Bold',...
                    'String', 'Mixed Data Type Ratio Split');
                
mixed_ratio_editbox = uicontrol(subpnl5,'style','edit',...
                    'units', 'normalized',...
                    'HorizontalAlignment', 'center', ...
                    'String', '15 15', ...
                    'position', [0.06 0.15 0.3 0.3]);   
                
mixed_randomise = uicontrol(subpnl5,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.4 0.6 0.6 0.3],...
                    'FontSize', 8, ...
                    'FontWeight', 'Bold',...
                    'String', 'Mixed Data Type-Randomise');
                
mixed_randomise_editbox = uicontrol(subpnl5,'style','edit',...
                    'units', 'normalized',...
                    'HorizontalAlignment', 'center', ...
                    'String', 'Yes', ...
                    'position', [0.6 0.3 0.3 0.3]);  
                
static_text = uicontrol(subpnl5,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.65 0.1 0.2 0.2],...
                    'FontSize', 8, ...
                    'FontWeight', 'normal',...
                    'String', 'Yes or No?');

%BOTTOM CENTRE RIGHT: SCREEN SETUP============================================
pnl3 = uipanel(fig,'Title','Probe Settings','FontSize',12, 'FontWeight','Bold',...
                'BackgroundColor','white',...
                'Position',[0.36 0.05 0.61 0.345]);
            
subpnl6 = uipanel(pnl3,'Position',[0.05, 0.4, 0.9, 0.5]);   

subpnl7 = uibuttongroup(pnl3,'Visible','off',...
                  'Position',[0.05, 0.05, 0.9, 0.35],...
                  'SelectionChangedFcn',@probe_selection);
            



%PROBE SETTINGS: CORRECT TO INCORRECT RATIO

probe_settings = uicontrol(subpnl6,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.2 0.6 0.6 0.3],...
                    'FontSize', 8, ...
                    'FontWeight', 'Bold',...
                    'String', 'Specify: Correct vs Incorrect');

percentage_settings = uicontrol(subpnl6,'Style', 'Text',... 
                    'Units', 'Normalized',... 
                    'Position', [0.01 0.05 0.2 1],...
                    'FontSize', 8, ...
                    'FontWeight', 'normal',...
                    'String', 'Percentage of Correct Probes Per Trial');
                
percentage_editbox = uicontrol(subpnl6,'style','edit',...
                    'units', 'normalized',...
                    'HorizontalAlignment', 'center', ...
                    'String', '50',...
                    'position', [0.35 0.1 0.3 0.3]);
                

                
% Create three radio buttons in the button group.
p1 = uicontrol(subpnl7,'Style',...
                  'radiobutton',...
                  'String','Randomise',...
                  'Position',[200 10 110 30],...
                  'HorizontalAlignment', 'left',...
                  'HandleVisibility','off');
              
p2 = uicontrol(subpnl7,'Style','radiobutton',...
                  'String','No-Randomisation',...
                  'Position',[20 10 110 30],...
                  'HorizontalAlignment', 'right',...
                  'HandleVisibility','off');
              
 
apply_button = uicontrol(fig,'style', 'pushbutton',... 
                    'string', 'Apply Settings', ...
                    'units', 'normalized',... 
                    'position', [0.77 0.86 0.2 0.06],... 
                    'callback', {@ApplySettings1,mem_load_editbox,Items_load_editbox,Trails_load_editbox,...
                                subpnl3, percentage_editbox, subpnl7, number_range_editbox,...
                                letter_range_editbox,mixed_ratio_editbox,mixed_randomise_editbox, r2_caps});
              
 %LEFTSIDE RADIO BUTTONS              
% Make the uibuttongroup visible after creating child objects. 
subpnl3.Visible = 'on';
 subpnl7.Visible = 'on';
 
 function ApplySettings1(source, event, mem_load_editbox,Items_load_editbox,Trails_load_editbox,...
                                subpnl3, percentage_editbox, subpnl7, number_range_editbox,...
                                letter_range_editbox,mixed_ratio_editbox,mixed_randomise_editbox, r2_caps)
   
 

Oricle_GUI_Handler('MemoryLoad',mem_load_editbox.String,'ItemsPerMem',Items_load_editbox.String,...
                    'TrialsPerMem',Trails_load_editbox.String,...
                    'DataType', subpnl3.SelectedObject.String,'Percentage', percentage_editbox.String,...
                     'ProbeRandom',subpnl7.SelectedObject.String,...
                    'NumberRange',number_range_editbox.String, 'LetterRange',letter_range_editbox.String,...
                    'MixedRatioSplit',mixed_ratio_editbox.String, 'MixedRandom',mixed_randomise_editbox.String,...
                    'Capitalise', r2_caps.Value)
                            

 end 
 
 function[number_range_editbox, letter_range_editbox, mixed_ratio_editbox,mixed_randomise_editbox] =  ApplySettings2(source, event, number_range_editbox, letter_range_editbox,...
                           mixed_ratio_editbox,mixed_randomise_editbox)
 
 
 
 end 
 
 function ApplySettingsTotal(table1, table2)
 
 end 
 
    function data_type_selection(source,event)
       display(['Previous: ' event.OldValue.String]);
       display(['Current: ' event.NewValue.String]);
       disp('------------------');
    end
    


    function probe_selection(source,event)
       display(['Previous: ' event.OldValue.String]);
       display(['Current: ' event.NewValue.String]);
       disp('------------------');
    end

    function back_button_function(source, event)
        Main_Menu();
        close(fig);
    end 
end 
