 function [filename, path, full_path, varargout] = OpenFileFunc(Dialogbox_txt, FileNames)
 
 %The Function Creates an open File Window For the user to input data.
 %The filenames are then checked to verify if the inputted files were
 %generated by the app. Certain files must be enetred at spesfic request
 %stages.
 try 
     if ~isvector(FileNames) || ~iscell(FileNames)
         error('ERROR: FileNames Entered to open Must be vector and a Cell Array');
     end
  
 FileNameLen = length(FileNames);    
 %Fileneame must be a vector of characters
 [filename,path] = uigetfile(Dialogbox_txt);
 if isempty(filename) || isempty(path)
     error('No file Selected')
 end 
 full_path = convertCharsToStrings(strcat(path, filename));

 for t = 1:FileNameLen
     scope1 = FileNames{t};  
    load(full_path, scope1);
 end 
 %RequestedVars = cell(1, length(FileNames));
 for p = 1:FileNameLen
     scope2 = FileNames{p};
     if ~exist(scope2, 'var')
         error('ERROR: When the .MAT file was opened the system could not find the required variables in the workspace');
     end   
     varargout{p} = eval(scope2);
     %RequestedVars{j, 2} = eval(scope2);
 end 
 
 %check that the variables loaded in correctly.
 
 
 catch Exception
     if strcmp(Exception.message,'ERROR: When the .MAT file was opened the system could not find the required variables in the workspace')
        questdlg('ERROR: The Selected Data is Incompatible with This App. Please use a File that was generated Using the Sternberg app',...
                   'ERROR','OK', 'OK');
     elseif strcmp(Exception.message, 'No file Selected')
         questdlg('Data Selection has been cancelled', 'OK', 'OK', 'OK');
     end 
           
 end 
 end 
